/** @type {import('tailwindcss').Config} */
const tokens = {
  buttonMaxWidth: "310px",
  calendarWidth: "284px",
  cardHeight: "200px",
  cardIconInnerSize: "51.333px",
  cardIconOuterSize: "70px",
  cardIconSize: "30px",
  contentMaxWidth: "960px",
  controlHeight: "40px",
  headerActionsGap: "16px",
  headerAvatarSize: "32px",
  headerBadgeSize: "20px",
  headerNotificationSize: "26px",
  featureCardWidth: "292px",
  heroContentWidth: "354px",
  heroHeight: "322px",
  modalMaxWidth: "400px",
  toastIconSize: "26px",
  tooltipMaxWidth: "340px",
  toggleThumbSize: "14px",
  toggleTrackHeight: "18px",
  calendarCellSize: "36px",
  calendarNavSize: "32px",
};

const themeColors = {
  background: "#ffffff",
  border: "#e3e3e3",
  danger: "#e51c00",
  green: {
    10: "#2ED389",
  },
  primary: {
    DEFAULT: "#c530c5",
    foreground: "#ffffff",
    dark: "#561056",
  },
  secondary: {
    DEFAULT: "#fbcffb",
    foreground: "#340634",
  },
  text: {
    DEFAULT: "#303030",
    secondary: "#616161",
  },
  muted: "#b5b5b5",
  tooltip: "#303030",
  track: "#d9d9d9",
  surface: {
    DEFAULT: "#ffffff",
    hover: "#fafafa",
  },
  magenta: {
    1: "#fffdff",
    2: "#fff5ff",
    3: "#fdeffd",
    4: "#fee7fe",
    7: "#fbcffb",
    8: "#f9bef9",
    9: "#f8b1f8",
    10: "#f68df6",
    11: "#e156e1",
    12: "#c530c5",
    13: "#9f269f",
    14: "#791a79",
    15: "#561056",
    16: "#340634",
  },
};

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: themeColors,
      fontSize: {
        body: ["16px", { lineHeight: "1.4" }],
        caption: ["12px", { lineHeight: "1.35" }],
        helper: ["12px", { lineHeight: "1.5" }],
        "hero-title": ["28px", { lineHeight: "1.4" }],
        label: ["14px", { lineHeight: "1.4" }],
        "modal-title": ["20px", { lineHeight: "1.35" }],
        "page-title": ["18px", { lineHeight: "1.4" }],
      },
      fontFamily: {
        primary: ['"Plus Jakarta Sans"', "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      maxWidth: {
        button: tokens.buttonMaxWidth,
        calendar: tokens.calendarWidth,
        content: tokens.contentMaxWidth,
        "feature-card": tokens.featureCardWidth,
        "hero-content": tokens.heroContentWidth,
        modal: tokens.modalMaxWidth,
        tooltip: tokens.tooltipMaxWidth,
      },
      width: {
        calendar: tokens.calendarWidth,
        sidebar: "188px",
        "toggle-track": "34px",
      },
      spacing: {
        "card-height": tokens.cardHeight,
        "card-icon": tokens.cardIconSize,
        "card-icon-inner": tokens.cardIconInnerSize,
        "card-icon-outer": tokens.cardIconOuterSize,
        "header-actions": tokens.headerActionsGap,
        "header-avatar": tokens.headerAvatarSize,
        "header-badge": tokens.headerBadgeSize,
        "header-notification": tokens.headerNotificationSize,
        "calendar-cell": tokens.calendarCellSize,
        "calendar-nav": tokens.calendarNavSize,
        control: tokens.controlHeight,
        "feature-card-art-height": "211px",
        "feature-card-art-left": "-31px",
        "feature-card-art-top": "-59px",
        "feature-card-art-width": "545px",
        "feature-card-copy-left": "15px",
        "feature-card-copy-top": "109px",
        "feature-card-copy-width": "260px",
        "feature-card": tokens.featureCardWidth,
        "feature-grid-horizontal-padding": "14px",
        "feature-grid-overlap": "58px",
        "hero-content-top": "60px",
        "page-header-gap": "56px",
        hero: tokens.heroHeight,
        "toast-icon": tokens.toastIconSize,
        "toggle-thumb": tokens.toggleThumbSize,
        "toggle-track": tokens.toggleTrackHeight,
      },
      boxShadow: {
        card: "0 7px 10px 0 rgba(0, 0, 0, 0.05)",
        modal: "0px 4px 2px 0px rgba(48,48,48,0.04),0px 16px 32px -4px rgba(48,48,48,0.1)",
        popup: "0px 16px 32px 0px rgba(48,48,48,0.1),0px 4px 2px 0px rgba(48,48,48,0.04)",
        toast: "0px 16px 32px 0px rgba(48,48,48,0.18),0px 4px 2px 0px rgba(48,48,48,0.08)",
        tooltip: "0px 16px 32px 0px rgba(48,48,48,0.14),0px 4px 2px 0px rgba(48,48,48,0.08)",
        "toggle-thumb": "0px 1px 2px rgba(0,0,0,0.2)",
      },
      borderRadius: {
        button: "10px",
        card: "8px",
        "card-icon-inner": "8.752px",
        "card-icon-outer": "13.128px",
        "calendar-cell": "8px",
        "calendar-nav": "8px",
        "calendar-popover": "8px",
        field: "12px",
        hero: "16px",
        modal: "12px",
        popover: "16px",
        toast: "22px",
        tooltip: "14px",
      },
      gridTemplateColumns: {
        "feature-cards": "repeat(3, 292px)",
      },
      inset: {
        "toggle-thumb-disabled": "2px",
        "toggle-thumb-enabled": "18px",
      },
    },
  },
  plugins: [],
};
